name: Deploy to Cloud Run

on:
  push:
    branches: ['main']

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-northeast1
  REPO_NAME: app-repo
  # TerraformのOutputで出たURLをここに設定します
  BACKEND_URL: https://celestial-backend-qzdsdfovsq-an.a.run.app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      # 1. Google Cloud 認証
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SA }}

      # 2. Docker 認証
      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # 3. Build & Push (Backend)
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./src/backend
          # ※本番用Dockerfileがない場合は Dockerfile.dev を指定
          file: ./src/backend/Dockerfile.dev
          push: true
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/backend:${{ github.sha }}

      # 4. Deploy to Cloud Run (Backend)
      - name: Deploy Backend
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: celestial-backend
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/backend:${{ github.sha }}

      # 5. Build & Push (Frontend)
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./src/frontend
          # ※本番用Dockerfileがない場合は Dockerfile.dev を指定
          file: ./src/frontend/Dockerfile.dev
          push: true
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/frontend:${{ github.sha }}
          # フロントエンドのビルド時にAPIのURLを埋め込む
          build-args: |
            NEXT_PUBLIC_API_URL=${{ env.BACKEND_URL }}

      # 6. Deploy to Cloud Run (Frontend)
      - name: Deploy Frontend
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: celestial-frontend
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/frontend:${{ github.sha }}